/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookConsultationRouteImport } from './routes/book-consultation'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TreatmentsRouteImport } from './routes/treatments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConsultationRoute = BookConsultationRouteImport.update({
  id: '/book-consultation',
  path: '/book-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-consultation': typeof BookConsultationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/treatments': typeof TreatmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-consultation': typeof BookConsultationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/treatments': typeof TreatmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-consultation': typeof BookConsultationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/treatments': typeof TreatmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/book-consultation' | '/sitemap.xml' | '/treatments'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/book-consultation' | '/sitemap.xml' | '/treatments'
  id: '__root__' | '/' | '/book-consultation' | '/sitemap.xml' | '/treatments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookConsultationRoute: typeof BookConsultationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TreatmentsRoute: typeof TreatmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-consultation': {
      id: '/book-consultation'
      path: '/book-consultation'
      fullPath: '/book-consultation'
      preLoaderRoute: typeof BookConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookConsultationRoute: BookConsultationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TreatmentsRoute: TreatmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
